import type { HouseSpec, TemplateMeta } from "./types";

export const DEFAULT_SPEC: HouseSpec = {
  name: "Family Villa",
  templateId: "family-villa",
  plotWidth: 46,
  plotLength: 58,
  bedrooms: 4,
  bathrooms: 3,
  includeVerandah: true,
  includePassage: true,
  livingRoomWidthPct: 48,
  kitchenWidthPct: 32,
  bedroomSize: 14,
  roofStyle: "hip",
  floorHeight: 11,
  wallThickness: 9,
  stories: 2,
  style: "Villa",
};

export const TEMPLATES: TemplateMeta[] = [
  {
    id: "family-villa",
    name: "Family Villa",
    tagline: "Spacious two-storey",
    description: "A generous family house with a deep verandah, hip roof and room to grow upstairs.",
    cover: "/templates/family-villa.jpg",
    bedrooms: 4,
    bathrooms: 3,
    style: "Villa",
    roof: "hip",
    roofLabel: "Hip Roof",
    plotHint: "40–50 ft",
    minWidth: 40,
    minLength: 50,
    stories: 2,
    spec: {
      plotWidth: 46,
      plotLength: 58,
      bedrooms: 4,
      bathrooms: 3,
      stories: 2,
      roofStyle: "hip",
      livingRoomWidthPct: 48,
      kitchenWidthPct: 32,
      bedroomSize: 14,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 11,
      style: "Villa",
    },
  },
  {
    id: "modern-bungalow",
    name: "Modern Bungalow",
    tagline: "Sleek single-floor",
    description: "Open living, a flat roof and clean lines — a contemporary one-storey bungalow.",
    cover: "/templates/modern-bungalow.jpg",
    bedrooms: 3,
    bathrooms: 2,
    style: "Modern",
    roof: "flat",
    roofLabel: "Flat Roof",
    plotHint: "35–45 ft",
    minWidth: 35,
    minLength: 45,
    stories: 1,
    spec: {
      plotWidth: 40,
      plotLength: 52,
      bedrooms: 3,
      bathrooms: 2,
      stories: 1,
      roofStyle: "flat",
      livingRoomWidthPct: 52,
      kitchenWidthPct: 30,
      bedroomSize: 13,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 10.5,
      wallThickness: 8,
      style: "Modern",
    },
  },
  {
    id: "compact-cottage",
    name: "Compact Cottage",
    tagline: "Charming space-saver",
    description: "A tight gable cottage that still fits a verandah, kitchen and two bedrooms.",
    cover: "/templates/compact-cottage.jpg",
    bedrooms: 2,
    bathrooms: 1,
    style: "Cottage",
    roof: "gable",
    roofLabel: "Gable",
    plotHint: "24–30 ft",
    minWidth: 28,
    minLength: 40,
    stories: 1,
    spec: {
      plotWidth: 30,
      plotLength: 42,
      bedrooms: 2,
      bathrooms: 1,
      stories: 1,
      roofStyle: "gable",
      livingRoomWidthPct: 50,
      kitchenWidthPct: 36,
      bedroomSize: 12,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 10,
      wallThickness: 8,
      style: "Cottage",
    },
  },
  {
    id: "shed-retreat",
    name: "Shed Retreat",
    tagline: "Bold slatted roof",
    description: "A single-slope shed roof retreat with a wide opening to the garden.",
    cover: "/templates/shed-retreat.jpg",
    bedrooms: 2,
    bathrooms: 1,
    style: "Retreat",
    roof: "shed",
    roofLabel: "Shed",
    plotHint: "30–42 ft",
    minWidth: 32,
    minLength: 42,
    stories: 1,
    spec: {
      plotWidth: 36,
      plotLength: 48,
      bedrooms: 2,
      bathrooms: 1,
      stories: 1,
      roofStyle: "shed",
      livingRoomWidthPct: 55,
      kitchenWidthPct: 34,
      bedroomSize: 13,
      includeVerandah: true,
      includePassage: false,
      floorHeight: 11,
      wallThickness: 8,
      style: "Retreat",
    },
  },
  {
    id: "tiny-home",
    name: "Tiny Home",
    tagline: "One bedroom, well planned",
    description: "A small single-bedroom house with living, kitchen, bath and a front verandah.",
    cover: "/templates/tiny-home.jpg",
    bedrooms: 1,
    bathrooms: 1,
    style: "Cottage",
    roof: "hip",
    roofLabel: "Hip Roof",
    plotHint: "30 × 40 ft",
    minWidth: 28,
    minLength: 38,
    stories: 1,
    spec: {
      plotWidth: 30,
      plotLength: 40,
      bedrooms: 1,
      bathrooms: 1,
      stories: 1,
      roofStyle: "hip",
      livingRoomWidthPct: 58,
      kitchenWidthPct: 40,
      bedroomSize: 12,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 10,
      style: "Cottage",
    },
  },
  {
    id: "country-house",
    name: "Country House",
    tagline: "Four-bed with verandahs",
    description: "A large country house with wraparound outdoor rooms and four bedrooms.",
    cover: "/templates/country-house.jpg",
    bedrooms: 4,
    bathrooms: 3,
    style: "Country",
    roof: "hip",
    roofLabel: "Hip Roof",
    plotHint: "48–60 ft",
    minWidth: 44,
    minLength: 56,
    stories: 2,
    spec: {
      plotWidth: 52,
      plotLength: 64,
      bedrooms: 4,
      bathrooms: 3,
      stories: 2,
      roofStyle: "hip",
      livingRoomWidthPct: 46,
      kitchenWidthPct: 30,
      bedroomSize: 15,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 11.5,
      style: "Country",
    },
  },
  {
    id: "konkan-cottage",
    name: "Konkan Cottage",
    tagline: "Coastal hip-roof home",
    description: "Parametric Konkan cottage: verandah, living, kitchen, bedroom and a rear padvi.",
    cover: "/templates/konkan-cottage.jpg",
    bedrooms: 1,
    bathrooms: 1,
    style: "Konkan",
    roof: "hip",
    roofLabel: "Hip Roof",
    plotHint: "30 × 46 ft",
    minWidth: 30,
    minLength: 44,
    stories: 1,
    spec: {
      plotWidth: 32,
      plotLength: 46,
      bedrooms: 1,
      bathrooms: 1,
      stories: 1,
      roofStyle: "hip",
      livingRoomWidthPct: 44,
      kitchenWidthPct: 38,
      bedroomSize: 13,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 10.5,
      style: "Konkan",
    },
  },
  {
    id: "five-bed-villa",
    name: "Five Bedroom Villa",
    tagline: "Two-storey, let the upper floor",
    description: "Ground-floor residence plus an upper floor of bedrooms with attached baths.",
    cover: "/templates/five-bed-villa.jpg",
    bedrooms: 5,
    bathrooms: 3,
    style: "Villa",
    roof: "hip",
    roofLabel: "Hip Roof",
    plotHint: "50–60 ft",
    minWidth: 48,
    minLength: 60,
    stories: 2,
    spec: {
      plotWidth: 54,
      plotLength: 68,
      bedrooms: 5,
      bathrooms: 3,
      stories: 2,
      roofStyle: "hip",
      livingRoomWidthPct: 50,
      kitchenWidthPct: 28,
      bedroomSize: 14,
      includeVerandah: true,
      includePassage: true,
      floorHeight: 11,
      style: "Villa",
    },
  },
];

export function specFromTemplate(id: string): HouseSpec {
  const t = TEMPLATES.find((x) => x.id === id) ?? TEMPLATES[0];
  return {
    ...DEFAULT_SPEC,
    ...t.spec,
    name: t.name,
    templateId: t.id,
    bedrooms: t.spec.bedrooms ?? t.bedrooms,
    bathrooms: t.spec.bathrooms ?? t.bathrooms,
    roofStyle: t.spec.roofStyle ?? t.roof,
    stories: t.spec.stories ?? t.stories,
    style: t.spec.style ?? t.style,
  };
}

export const ROOF_LABEL: Record<HouseSpec["roofStyle"], string> = {
  hip: "Hip Roof",
  gable: "Gable",
  shed: "Shed",
  flat: "Flat Roof",
};
