/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnzaRouteImport } from './routes/anza'
import { Route as KuhusuRouteImport } from './routes/kuhusu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MsaadaRouteImport } from './routes/msaada'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WasilianaRouteImport } from './routes/wasiliana'
import { Route as AnzaIndexRouteImport } from './routes/anza/index'
import { Route as AnzaAgizaRouteImport } from './routes/anza/agiza'
import { Route as AnzaDesignRouteImport } from './routes/anza/design'
import { Route as AnzaEngineerRouteImport } from './routes/anza/engineer'
import { Route as AnzaGharamaRouteImport } from './routes/anza/gharama'
import { Route as AnzaInteriorRouteImport } from './routes/anza/interior'
import { Route as AnzaMradiRouteImport } from './routes/anza/mradi'
import { Route as AnzaMshauriRouteImport } from './routes/anza/mshauri'
import { Route as AnzaSheriaRouteImport } from './routes/anza/sheria'
import { Route as AnzaVifaaRouteImport } from './routes/anza/vifaa'
import { Route as AnzaWadiRouteImport } from './routes/anza/wadi'
import { Route as AnzaWataalamuRouteImport } from './routes/anza/wataalamu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnzaRoute = AnzaRouteImport.update({
  id: '/anza',
  path: '/anza',
  getParentRoute: () => rootRouteImport,
} as any)
const KuhusuRoute = KuhusuRouteImport.update({
  id: '/kuhusu',
  path: '/kuhusu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MsaadaRoute = MsaadaRouteImport.update({
  id: '/msaada',
  path: '/msaada',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WasilianaRoute = WasilianaRouteImport.update({
  id: '/wasiliana',
  path: '/wasiliana',
  getParentRoute: () => rootRouteImport,
} as any)
const AnzaIndexRoute = AnzaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaAgizaRoute = AnzaAgizaRouteImport.update({
  id: '/agiza',
  path: '/agiza',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaDesignRoute = AnzaDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaEngineerRoute = AnzaEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaGharamaRoute = AnzaGharamaRouteImport.update({
  id: '/gharama',
  path: '/gharama',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaInteriorRoute = AnzaInteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaMradiRoute = AnzaMradiRouteImport.update({
  id: '/mradi',
  path: '/mradi',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaMshauriRoute = AnzaMshauriRouteImport.update({
  id: '/mshauri',
  path: '/mshauri',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaSheriaRoute = AnzaSheriaRouteImport.update({
  id: '/sheria',
  path: '/sheria',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaVifaaRoute = AnzaVifaaRouteImport.update({
  id: '/vifaa',
  path: '/vifaa',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaWadiRoute = AnzaWadiRouteImport.update({
  id: '/wadi',
  path: '/wadi',
  getParentRoute: () => AnzaRoute,
} as any)
const AnzaWataalamuRoute = AnzaWataalamuRouteImport.update({
  id: '/wataalamu',
  path: '/wataalamu',
  getParentRoute: () => AnzaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anza': typeof AnzaRouteWithChildren
  '/kuhusu': typeof KuhusuRoute
  '/login': typeof LoginRoute
  '/msaada': typeof MsaadaRoute
  '/register': typeof RegisterRoute
  '/wasiliana': typeof WasilianaRoute
  '/anza/agiza': typeof AnzaAgizaRoute
  '/anza/design': typeof AnzaDesignRoute
  '/anza/engineer': typeof AnzaEngineerRoute
  '/anza/gharama': typeof AnzaGharamaRoute
  '/anza/interior': typeof AnzaInteriorRoute
  '/anza/mradi': typeof AnzaMradiRoute
  '/anza/mshauri': typeof AnzaMshauriRoute
  '/anza/sheria': typeof AnzaSheriaRoute
  '/anza/vifaa': typeof AnzaVifaaRoute
  '/anza/wadi': typeof AnzaWadiRoute
  '/anza/wataalamu': typeof AnzaWataalamuRoute
  '/anza/': typeof AnzaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kuhusu': typeof KuhusuRoute
  '/login': typeof LoginRoute
  '/msaada': typeof MsaadaRoute
  '/register': typeof RegisterRoute
  '/wasiliana': typeof WasilianaRoute
  '/anza/agiza': typeof AnzaAgizaRoute
  '/anza/design': typeof AnzaDesignRoute
  '/anza/engineer': typeof AnzaEngineerRoute
  '/anza/gharama': typeof AnzaGharamaRoute
  '/anza/interior': typeof AnzaInteriorRoute
  '/anza/mradi': typeof AnzaMradiRoute
  '/anza/mshauri': typeof AnzaMshauriRoute
  '/anza/sheria': typeof AnzaSheriaRoute
  '/anza/vifaa': typeof AnzaVifaaRoute
  '/anza/wadi': typeof AnzaWadiRoute
  '/anza/wataalamu': typeof AnzaWataalamuRoute
  '/anza': typeof AnzaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anza': typeof AnzaRouteWithChildren
  '/kuhusu': typeof KuhusuRoute
  '/login': typeof LoginRoute
  '/msaada': typeof MsaadaRoute
  '/register': typeof RegisterRoute
  '/wasiliana': typeof WasilianaRoute
  '/anza/agiza': typeof AnzaAgizaRoute
  '/anza/design': typeof AnzaDesignRoute
  '/anza/engineer': typeof AnzaEngineerRoute
  '/anza/gharama': typeof AnzaGharamaRoute
  '/anza/interior': typeof AnzaInteriorRoute
  '/anza/mradi': typeof AnzaMradiRoute
  '/anza/mshauri': typeof AnzaMshauriRoute
  '/anza/sheria': typeof AnzaSheriaRoute
  '/anza/vifaa': typeof AnzaVifaaRoute
  '/anza/wadi': typeof AnzaWadiRoute
  '/anza/wataalamu': typeof AnzaWataalamuRoute
  '/anza/': typeof AnzaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anza'
    | '/kuhusu'
    | '/login'
    | '/msaada'
    | '/register'
    | '/wasiliana'
    | '/anza/agiza'
    | '/anza/design'
    | '/anza/engineer'
    | '/anza/gharama'
    | '/anza/interior'
    | '/anza/mradi'
    | '/anza/mshauri'
    | '/anza/sheria'
    | '/anza/vifaa'
    | '/anza/wadi'
    | '/anza/wataalamu'
    | '/anza/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kuhusu'
    | '/login'
    | '/msaada'
    | '/register'
    | '/wasiliana'
    | '/anza/agiza'
    | '/anza/design'
    | '/anza/engineer'
    | '/anza/gharama'
    | '/anza/interior'
    | '/anza/mradi'
    | '/anza/mshauri'
    | '/anza/sheria'
    | '/anza/vifaa'
    | '/anza/wadi'
    | '/anza/wataalamu'
    | '/anza'
  id:
    | '__root__'
    | '/'
    | '/anza'
    | '/kuhusu'
    | '/login'
    | '/msaada'
    | '/register'
    | '/wasiliana'
    | '/anza/agiza'
    | '/anza/design'
    | '/anza/engineer'
    | '/anza/gharama'
    | '/anza/interior'
    | '/anza/mradi'
    | '/anza/mshauri'
    | '/anza/sheria'
    | '/anza/vifaa'
    | '/anza/wadi'
    | '/anza/wataalamu'
    | '/anza/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnzaRoute: typeof AnzaRouteWithChildren
  KuhusuRoute: typeof KuhusuRoute
  LoginRoute: typeof LoginRoute
  MsaadaRoute: typeof MsaadaRoute
  RegisterRoute: typeof RegisterRoute
  WasilianaRoute: typeof WasilianaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anza': {
      id: '/anza'
      path: '/anza'
      fullPath: '/anza'
      preLoaderRoute: typeof AnzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuhusu': {
      id: '/kuhusu'
      path: '/kuhusu'
      fullPath: '/kuhusu'
      preLoaderRoute: typeof KuhusuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msaada': {
      id: '/msaada'
      path: '/msaada'
      fullPath: '/msaada'
      preLoaderRoute: typeof MsaadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wasiliana': {
      id: '/wasiliana'
      path: '/wasiliana'
      fullPath: '/wasiliana'
      preLoaderRoute: typeof WasilianaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anza/': {
      id: '/anza/'
      path: '/'
      fullPath: '/anza/'
      preLoaderRoute: typeof AnzaIndexRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/agiza': {
      id: '/anza/agiza'
      path: '/agiza'
      fullPath: '/anza/agiza'
      preLoaderRoute: typeof AnzaAgizaRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/design': {
      id: '/anza/design'
      path: '/design'
      fullPath: '/anza/design'
      preLoaderRoute: typeof AnzaDesignRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/engineer': {
      id: '/anza/engineer'
      path: '/engineer'
      fullPath: '/anza/engineer'
      preLoaderRoute: typeof AnzaEngineerRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/gharama': {
      id: '/anza/gharama'
      path: '/gharama'
      fullPath: '/anza/gharama'
      preLoaderRoute: typeof AnzaGharamaRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/interior': {
      id: '/anza/interior'
      path: '/interior'
      fullPath: '/anza/interior'
      preLoaderRoute: typeof AnzaInteriorRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/mradi': {
      id: '/anza/mradi'
      path: '/mradi'
      fullPath: '/anza/mradi'
      preLoaderRoute: typeof AnzaMradiRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/mshauri': {
      id: '/anza/mshauri'
      path: '/mshauri'
      fullPath: '/anza/mshauri'
      preLoaderRoute: typeof AnzaMshauriRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/sheria': {
      id: '/anza/sheria'
      path: '/sheria'
      fullPath: '/anza/sheria'
      preLoaderRoute: typeof AnzaSheriaRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/vifaa': {
      id: '/anza/vifaa'
      path: '/vifaa'
      fullPath: '/anza/vifaa'
      preLoaderRoute: typeof AnzaVifaaRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/wadi': {
      id: '/anza/wadi'
      path: '/wadi'
      fullPath: '/anza/wadi'
      preLoaderRoute: typeof AnzaWadiRouteImport
      parentRoute: typeof AnzaRoute
    }
    '/anza/wataalamu': {
      id: '/anza/wataalamu'
      path: '/wataalamu'
      fullPath: '/anza/wataalamu'
      preLoaderRoute: typeof AnzaWataalamuRouteImport
      parentRoute: typeof AnzaRoute
    }
  }
}

interface AnzaRouteChildren {
  AnzaAgizaRoute: typeof AnzaAgizaRoute
  AnzaDesignRoute: typeof AnzaDesignRoute
  AnzaEngineerRoute: typeof AnzaEngineerRoute
  AnzaGharamaRoute: typeof AnzaGharamaRoute
  AnzaInteriorRoute: typeof AnzaInteriorRoute
  AnzaMradiRoute: typeof AnzaMradiRoute
  AnzaMshauriRoute: typeof AnzaMshauriRoute
  AnzaSheriaRoute: typeof AnzaSheriaRoute
  AnzaVifaaRoute: typeof AnzaVifaaRoute
  AnzaWadiRoute: typeof AnzaWadiRoute
  AnzaWataalamuRoute: typeof AnzaWataalamuRoute
  AnzaIndexRoute: typeof AnzaIndexRoute
}

const AnzaRouteChildren: AnzaRouteChildren = {
  AnzaAgizaRoute: AnzaAgizaRoute,
  AnzaDesignRoute: AnzaDesignRoute,
  AnzaEngineerRoute: AnzaEngineerRoute,
  AnzaGharamaRoute: AnzaGharamaRoute,
  AnzaInteriorRoute: AnzaInteriorRoute,
  AnzaMradiRoute: AnzaMradiRoute,
  AnzaMshauriRoute: AnzaMshauriRoute,
  AnzaSheriaRoute: AnzaSheriaRoute,
  AnzaVifaaRoute: AnzaVifaaRoute,
  AnzaWadiRoute: AnzaWadiRoute,
  AnzaWataalamuRoute: AnzaWataalamuRoute,
  AnzaIndexRoute: AnzaIndexRoute,
}

const AnzaRouteWithChildren = AnzaRoute._addFileChildren(AnzaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnzaRoute: AnzaRouteWithChildren,
  KuhusuRoute: KuhusuRoute,
  LoginRoute: LoginRoute,
  MsaadaRoute: MsaadaRoute,
  RegisterRoute: RegisterRoute,
  WasilianaRoute: WasilianaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
